version: 2.1

executors:
  node-executor:
    working_directory: ~/vendor-contract-mgmt-client
    docker:
      - image: cimg/node:17.2.0

jobs:
  lint-project:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: ESLint Project
          command: npm run lint
      - run:
          name: Prettier
          command: npm run format
      
  
  test-project:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Test Project
          command: npm run test

workflows:
  test-lint-project:
    jobs:
      - lint-project:
          filters:
            branches:
              ignore:
                - /main/
      - test-project:
          filters:
            branches:
              ignore:
                - /main/
