version: 2.1

executors:
  node-executor:
    working_directory: ~/vendor-contract-mgmt-service
    docker:
      - image: cimg/node:17.2.0

jobs:
  lint-project:
    executor: node-executor
    steps:
      - checkout
      - run: 
          command: npm install
      - run:
          name: ESLint Project
          command: npm run lint
      - run:
          name: Prettier
          command: npm run format

workflows:
  test-lint-project:
    jobs:
      - lint-project:
          filters:
            branches:
              ignore:
                - /main/
